CREATE DATABASE IF NOT EXISTS sla;
CREATE DATABASE IF NOT EXISTS users;
CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS incidents;
CREATE DATABASE IF NOT EXISTS notifications;
CREATE DATABASE IF NOT EXISTS reports;
